export const GET_SERVER_DATA = "GET_SERVER_DATA";
export const MARKET_SUMMERY_DATA_LOADED = "MARKET_SUMMERY_DATA_LOADED";

export const GET_QOUTE_SUMMERY_DATA = "GET_QOUTE_SUMMERY_DATA";
export const QOUTE_SUMMERY_DATA_LOADED = "QOUTE_SUMMERY_DATA_LOADED";

export const API_ERRORED = "API_ERRORED";

